import { GenerationRequest } from '../types';

export class ModelClientModule {
  public async streamGenerate(
    request: GenerationRequest,
    prompt: string,
    onChunk: (chunk: string) => void,
  ): Promise<void> {
    const apiKey = process.env.CPPUT_API_KEY;
    const endpoint = process.env.CPPUT_API_ENDPOINT;

    if (!apiKey || !endpoint) {
      const fallback = this.mockResponse(request, prompt);
      for (const chunk of fallback.match(/.{1,120}/g) ?? []) {
        onChunk(chunk);
        await new Promise((resolve) => setTimeout(resolve, 20));
      }
      return;
    }

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        stream: true,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok || !response.body) {
      throw new Error(`模型调用失败: ${response.status} ${response.statusText}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();

    let done = false;
    while (!done) {
      const result = await reader.read();
      done = result.done;
      if (done || !result.value) {
        break;
      }
      const text = decoder.decode(result.value, { stream: true });
      onChunk(text);
    }
  }

  private mockResponse(request: GenerationRequest, prompt: string): string {
    const names = request.methods.map((m) => m.name).join(', ');
    return `// Mock Stream Output\n// Selected methods: ${names}\n// Prompt length: ${prompt.length}\n#include <gtest/gtest.h>\n\nTEST(AutoGenerated, BasicCoverage) {\n  EXPECT_TRUE(true);\n}\n`;
  }
}
