from __future__ import annotations

import json
import os
import time
from typing import Callable
from urllib import error, request

from .types import GenerationRequest


class ModelClientModule:
    def stream_generate(self, req: GenerationRequest, prompt: str, on_chunk: Callable[[str], None]) -> None:
        api_key = self._first_env("CPPUT_API_KEY", "OPENAI_API_KEY", "API_KEY")
        endpoint = self._first_env("CPPUT_API_ENDPOINT", "OPENAI_BASE_URL", "API_ENDPOINT")

        if not api_key and not endpoint:
            self._stream_mock(req, prompt, on_chunk)
            return
        if not api_key or not endpoint:
            raise RuntimeError("模型配置不完整：请同时设置 API Key 与 Endpoint，或都不设置以使用 mock 模式")

        payload = json.dumps(
            {
                "stream": False,
                "messages": [{"role": "user", "content": prompt}],
            }
        ).encode("utf-8")

        req_obj = request.Request(
            endpoint,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )

        try:
            with request.urlopen(req_obj, timeout=120) as resp:
                body = resp.read().decode("utf-8", errors="ignore")
                text = self._extract_text(body)
                for chunk in self._split_chunks(text, 120):
                    on_chunk(chunk)
        except error.URLError as exc:
            raise RuntimeError(f"模型调用失败: {exc}") from exc

    def _extract_text(self, body: str) -> str:
        try:
            data = json.loads(body)
            choices = data.get("choices") or []
            if choices:
                msg = choices[0].get("message") or {}
                content = msg.get("content")
                if isinstance(content, str):
                    return content
        except json.JSONDecodeError:
            pass
        return body

    def _stream_mock(self, req: GenerationRequest, prompt: str, on_chunk: Callable[[str], None]) -> None:
        names = ", ".join(m.name for m in req.methods)
        text = (
            "// Mock Stream Output\n"
            f"// Selected methods: {names}\n"
            f"// Prompt length: {len(prompt)}\n"
            "#include <gtest/gtest.h>\n\n"
            "TEST(AutoGenerated, BasicCoverage) {\n"
            "  EXPECT_TRUE(true);\n"
            "}\n"
        )
        for chunk in self._split_chunks(text, 120):
            on_chunk(chunk)
            time.sleep(0.02)

    def _split_chunks(self, text: str, size: int):
        for i in range(0, len(text), size):
            yield text[i : i + size]

    def _first_env(self, *names: str) -> str | None:
        for name in names:
            value = os.getenv(name)
            if value and value.strip():
                return value.strip()
        return None
